name: build-uaa-test

on:
  workflow_dispatch:

jobs:
  # test templating before publishing a package
  prepare:
    name: Prepare Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: cloudfoundry/uaa
          ref: '4.32.0'
          path: src/docker/uaa/uaa
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'liberica'
      - name: Build UAA Test Image
        shell: bash
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        working-directory: ./src/docker/uaa
        run: ./build-uaa
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Test Image
        uses: docker/build-push-action@v6
        with:
          context: ./src/docker/uaa
          push: true
          tags: springcloud/scdf-uaa-test:4.32
